spring:
  config:
    activate:
      on-profile: h2-test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: never

jwt:
  access-secret: ${JWT_ACCESS_SECRET:jwtsecretkeydefaultfortestasdasdasdsadsadsa}
  refresh-secret: ${JWT_ACCESS_SECRET:jwtsecretkeydefaultfortestasdasdasdsadsadsa}