spring:
  config:
    activate:
      on-profile: postgresql-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ajou_way
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:create}
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 947997246064-fi5aft8oimhpc9enujjhbkltp823n0v1.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - email
#              - profile

jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_ACCESS_SECRET}