spring:
  application:
    name: ajouway

  profiles:
    group:
      test: h2-test
      dev: postgresql-dev

  config:
    import: "application-dev.yml,application-test.yml"

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace